AUTO-COMMIT on 2026-02-04 11:42:23

diff --git a/.github/workflows/run.yml b/.github/workflows/run.yml
--- a/.github/workflows/run.yml
+++ b/.github/workflows/run.yml
@@ -64,8 +64,26 @@ jobs:
           INVENTORY=inventory.ini
           cat > $INVENTORY <<EOF
           [edgepaas]
-          edgepaas-ec2 ansible_host=${EC2_IP} ansible_user=ec2-user ansible_python_interpreter=/usr/bin/python3 ansible_ssh_args='-o StrictHostKeyChecking=no'
+          edgepaas-ec2 ansible_host="${{ env.EC2_IP }}" ansible_user=ec2-user ansible_python_interpreter=/usr/bin/python3 ansible_ssh_args='-o StrictHostKeyChecking=no'
           EOF
+
+      - name: Check Whether Inventory was Really Created
+        run: |
+            INVENTORY=inventory.ini
+            if [ -f "$INVENTORY" ]; then
+              echo "✅ Inventory file created:"
+            else
+              echo "❌ Inventory file not found"
+              exit 1
+            fi
+
+
+            echo "Contents of inventory:"
+            cat "$INVENTORY"
+
+            echo "Showing lines that start with a number (likely an IP):"
+            grep -E '^[0-9]' "$INVENTORY" || echo "No lines starting with a number found"
+
 
       - name: Run Ansible
         run: |
