AUTO-COMMIT on 2026-02-04 16:37:43

diff --git a/.github/workflows/run.yml b/.github/workflows/run.yml
--- a/.github/workflows/run.yml
+++ b/.github/workflows/run.yml
@@ -62,8 +62,9 @@ jobs:
       - name: Check network connectivity
         run: |
           echo "Testing ping to EC2"
-          echo "EC2_IP = $EC2_IP"
-          ping -c 3 $EC2_IP || echo "Ping failed.. Issue with github Runner Connectivity"
+          EC2_IP_CLEAN="$(echo "${{ secrets.EC2_IP }}" | tr -d '[:space:]')"
+          echo "EC2_IP = $EC2_IP_CLEAN"
+          ping -c 3 "$EC2_IP_CLEAN" || echo "Ping failed.. Issue with github Runner Connectivity"
 
       - name: Setup SSH key
         run: |
